$ANSIBLE_VAULT;1.1;AES256
30666362366237636338636536333663326139366563336533643830333961663165323739636566
3530613866386436373362613962643233386430373564310a613934303634336134336163306633
36623930386166366666373138326361333963363031346139333637613564356665326534656363
3733613162383837340a303734383462306465376161663438626663623436626331346234396562
37346432326463653232666263316364353235643565643761666232366337316330396135363265
37623534336565303735653639633530613336316361343364393832326531303433323539363262
37663636383932316632616431646362303839646163373230313532336162653534316334626466
31313837666135323362
